version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  hedgie-gateways:
    build: .
    container_name: ${HEDGIE_GATEWAYS_CONTAINER_NAME}
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_NAME=${PG_NAME}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
