version: '3.8'

services:
  collectors:
    build: .
    container_name: hedgie-gateways
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DATABASE=${PG_DATABASE}
      - DERIBIT_ENABLED=${DERIBIT_ENABLED}
      - OKX_ENABLED=${OKX_ENABLED}
      - BINANCE_ENABLED=${BINANCE_ENABLED}
      - BYBIT_ENABLED=${BYBIT_ENABLED}
      - CME_ENABLED=${CME_ENABLED}
      - COLLECTION_INTERVAL=${COLLECTION_INTERVAL}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./logs:/app/logs
      - ./backups:/app/backups
    restart: unless-stopped
